openapi: 3.0.0
info:
  title: Cinema API Title
  version: 1.0.0
  description: API documentation for your application
tags:
  - name: Auth
    description: User authentication

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string
      responses:
        '201':
          description: Created Account Successfully
        '500':
          description: Error Creating Account

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Email or password incorrect

  /auth/reset:
    put:
      tags:
        - Auth
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                oldPassword:
                  type: string
      responses:
        '200':
          description: Password Updated
        '404':
          description: User not found

  /auth/forget:
    post:
      tags:
        - Auth
      summary: Forget password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: If this account exists, an email will be sent